### ISSUE TITLE
QDTrack based on YOLO-X detector

### ISSUE THREAD

**Issue by sanghoooon** [ethvis/qd-track#131]
Dear authors, 
thanks for your great work. 

I have read your updated manuscript on [arxiv](https://arxiv.org/abs/2210.06984), 
and was curious if you have a plan to make qdtrack implementation based on YOLO-X detector publicly available.

Thank you!

**Comment by rourouro** [comment]
Hello, I am very interested in your idea, I wonder if your idea has come true?

**Comment by fyu** [comment]
Yes, we plan to release the new models as well. Because we are also re-organizing the tracking code base, it is taking some time.

**Comment by rourouro** [comment]
Okay, thank you and I wish you all the best


------------------

W.osh
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: &nbsp;"Fisher ***@***.***&gt;;
Send time:&nbsp;Thursday, Jan 12, 2023 5:25 PM
***@***.***&gt;; 
***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [SysCV/qdtrack] QDTrack based on YOLO-X detector (Issue #131)





 
Yes, we plan to release the new models as well. Because we are also re-organizing the tracking code base, it is taking some time.
